export default {
  data: {
    github: {
      viewer: {
        contributionsCollection: {
          contributionCalendar: {
            totalContributions: 11301,
            weeks: [
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2018-12-09',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 6,
                    date: '2018-12-10',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2018-12-11',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 25,
                    date: '2018-12-12',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 8,
                    date: '2018-12-13',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2018-12-14',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 8,
                    date: '2018-12-15',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2018-12-16',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 4,
                    date: '2018-12-17',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 8,
                    date: '2018-12-18',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2018-12-19',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2018-12-20',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2018-12-21',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 32,
                    date: '2018-12-22',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 42,
                    date: '2018-12-23',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2018-12-24',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2018-12-25',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2018-12-26',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 5,
                    date: '2018-12-27',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2018-12-28',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2018-12-29',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2018-12-30',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 15,
                    date: '2018-12-31',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 8,
                    date: '2019-01-01',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-01-02',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-01-03',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-01-04',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-01-05',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-01-06',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 6,
                    date: '2019-01-07',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-01-08',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2019-01-09',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-01-10',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 3,
                    date: '2019-01-11',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 7,
                    date: '2019-01-12',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 7,
                    date: '2019-01-13',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 39,
                    date: '2019-01-14',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 31,
                    date: '2019-01-15',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 44,
                    date: '2019-01-16',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-01-17',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-01-18',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 68,
                    date: '2019-01-19',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 29,
                    date: '2019-01-20',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 25,
                    date: '2019-01-21',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-01-22',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-01-23',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-01-24',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-01-25',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 28,
                    date: '2019-01-26',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 31,
                    date: '2019-01-27',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-01-28',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-01-29',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 15,
                    date: '2019-01-30',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 43,
                    date: '2019-01-31',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-02-01',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-02-02',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#239a3b',
                    contributionCount: 73,
                    date: '2019-02-03',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-02-04',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 27,
                    date: '2019-02-05',
                    weekday: 2,
                  },
                  {
                    color: '#196127',
                    contributionCount: 95,
                    date: '2019-02-06',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-02-07',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2019-02-08',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 51,
                    date: '2019-02-09',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-02-10',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 32,
                    date: '2019-02-11',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-02-12',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 7,
                    date: '2019-02-13',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-02-14',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 50,
                    date: '2019-02-15',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 29,
                    date: '2019-02-16',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-02-17',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2019-02-18',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-02-19',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-02-20',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 32,
                    date: '2019-02-21',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-02-22',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 73,
                    date: '2019-02-23',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 22,
                    date: '2019-02-24',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 25,
                    date: '2019-02-25',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 53,
                    date: '2019-02-26',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 50,
                    date: '2019-02-27',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 8,
                    date: '2019-02-28',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 45,
                    date: '2019-03-01',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 67,
                    date: '2019-03-02',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 45,
                    date: '2019-03-03',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-03-04',
                    weekday: 1,
                  },
                  {
                    color: '#196127',
                    contributionCount: 95,
                    date: '2019-03-05',
                    weekday: 2,
                  },
                  {
                    color: '#196127',
                    contributionCount: 84,
                    date: '2019-03-06',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 48,
                    date: '2019-03-07',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 49,
                    date: '2019-03-08',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-03-09',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-03-10',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 50,
                    date: '2019-03-11',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 51,
                    date: '2019-03-12',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-03-13',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 41,
                    date: '2019-03-14',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-03-15',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 43,
                    date: '2019-03-16',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#196127',
                    contributionCount: 116,
                    date: '2019-03-17',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2019-03-18',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 56,
                    date: '2019-03-19',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 46,
                    date: '2019-03-20',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 47,
                    date: '2019-03-21',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2019-03-22',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 58,
                    date: '2019-03-23',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 40,
                    date: '2019-03-24',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 38,
                    date: '2019-03-25',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 60,
                    date: '2019-03-26',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 32,
                    date: '2019-03-27',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 41,
                    date: '2019-03-28',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-03-29',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 4,
                    date: '2019-03-30',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#196127',
                    contributionCount: 80,
                    date: '2019-03-31',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-04-01',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-04-02',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 45,
                    date: '2019-04-03',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-04-04',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-04-05',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 38,
                    date: '2019-04-06',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-04-07',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2019-04-08',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-04-09',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 43,
                    date: '2019-04-10',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-04-11',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-04-12',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 45,
                    date: '2019-04-13',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-04-14',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 39,
                    date: '2019-04-15',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 49,
                    date: '2019-04-16',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 38,
                    date: '2019-04-17',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 42,
                    date: '2019-04-18',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2019-04-19',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 40,
                    date: '2019-04-20',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 5,
                    date: '2019-04-21',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-04-22',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-04-23',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 38,
                    date: '2019-04-24',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-04-25',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-04-26',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 45,
                    date: '2019-04-27',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-04-28',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 21,
                    date: '2019-04-29',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 56,
                    date: '2019-04-30',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 29,
                    date: '2019-05-01',
                    weekday: 3,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 70,
                    date: '2019-05-02',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 15,
                    date: '2019-05-03',
                    weekday: 5,
                  },
                  {
                    color: '#196127',
                    contributionCount: 106,
                    date: '2019-05-04',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 15,
                    date: '2019-05-05',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 52,
                    date: '2019-05-06',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-05-07',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-05-08',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2019-05-09',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 22,
                    date: '2019-05-10',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 7,
                    date: '2019-05-11',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-05-12',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2019-05-13',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 38,
                    date: '2019-05-14',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 67,
                    date: '2019-05-15',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 50,
                    date: '2019-05-16',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 47,
                    date: '2019-05-17',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 1,
                    date: '2019-05-18',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 5,
                    date: '2019-05-19',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-05-20',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 76,
                    date: '2019-05-21',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-05-22',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 46,
                    date: '2019-05-23',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 15,
                    date: '2019-05-24',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 76,
                    date: '2019-05-25',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-05-26',
                    weekday: 0,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 62,
                    date: '2019-05-27',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 41,
                    date: '2019-05-28',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 60,
                    date: '2019-05-29',
                    weekday: 3,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 63,
                    date: '2019-05-30',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 53,
                    date: '2019-05-31',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 65,
                    date: '2019-06-01',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-06-02',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-06-03',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 54,
                    date: '2019-06-04',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 43,
                    date: '2019-06-05',
                    weekday: 3,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 79,
                    date: '2019-06-06',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-06-07',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 22,
                    date: '2019-06-08',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#239a3b',
                    contributionCount: 79,
                    date: '2019-06-09',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 43,
                    date: '2019-06-10',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-06-11',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 55,
                    date: '2019-06-12',
                    weekday: 3,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 67,
                    date: '2019-06-13',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 27,
                    date: '2019-06-14',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 68,
                    date: '2019-06-15',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-06-16',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-06-17',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 42,
                    date: '2019-06-18',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2019-06-19',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-06-20',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 45,
                    date: '2019-06-21',
                    weekday: 5,
                  },
                  {
                    color: '#196127',
                    contributionCount: 88,
                    date: '2019-06-22',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-06-23',
                    weekday: 0,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 62,
                    date: '2019-06-24',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-06-25',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 35,
                    date: '2019-06-26',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-06-27',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-06-28',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 70,
                    date: '2019-06-29',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#196127',
                    contributionCount: 102,
                    date: '2019-06-30',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 22,
                    date: '2019-07-01',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 32,
                    date: '2019-07-02',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-07-03',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-07-04',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 49,
                    date: '2019-07-05',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-07-06',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-07-07',
                    weekday: 0,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 54,
                    date: '2019-07-08',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-07-09',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-07-10',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 52,
                    date: '2019-07-11',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-07-12',
                    weekday: 5,
                  },
                  {
                    color: '#196127',
                    contributionCount: 87,
                    date: '2019-07-13',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#239a3b',
                    contributionCount: 62,
                    date: '2019-07-14',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 39,
                    date: '2019-07-15',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 45,
                    date: '2019-07-16',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 51,
                    date: '2019-07-17',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 39,
                    date: '2019-07-18',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 31,
                    date: '2019-07-19',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 70,
                    date: '2019-07-20',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-07-21',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2019-07-22',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-07-23',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 69,
                    date: '2019-07-24',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-07-25',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-07-26',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-07-27',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 6,
                    date: '2019-07-28',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2019-07-29',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 54,
                    date: '2019-07-30',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-07-31',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-08-01',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-08-02',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 52,
                    date: '2019-08-03',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-08-04',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-08-05',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 59,
                    date: '2019-08-06',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-08-07',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-08-08',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-08-09',
                    weekday: 5,
                  },
                  {
                    color: '#196127',
                    contributionCount: 87,
                    date: '2019-08-10',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-08-11',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-08-12',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-08-13',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-08-14',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-08-15',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 52,
                    date: '2019-08-16',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-08-17',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#239a3b',
                    contributionCount: 66,
                    date: '2019-08-18',
                    weekday: 0,
                  },
                  {
                    color: '#196127',
                    contributionCount: 89,
                    date: '2019-08-19',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 22,
                    date: '2019-08-20',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-08-21',
                    weekday: 3,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 66,
                    date: '2019-08-22',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-08-23',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-08-24',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 21,
                    date: '2019-08-25',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-08-26',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 15,
                    date: '2019-08-27',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 68,
                    date: '2019-08-28',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-08-29',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-08-30',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 30,
                    date: '2019-08-31',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-09-01',
                    weekday: 0,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 65,
                    date: '2019-09-02',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 27,
                    date: '2019-09-03',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 22,
                    date: '2019-09-04',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-09-05',
                    weekday: 4,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 67,
                    date: '2019-09-06',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-09-07',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-09-08',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 50,
                    date: '2019-09-09',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-09-10',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-09-11',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 5,
                    date: '2019-09-12',
                    weekday: 4,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 60,
                    date: '2019-09-13',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 7,
                    date: '2019-09-14',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 25,
                    date: '2019-09-15',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 25,
                    date: '2019-09-16',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 4,
                    date: '2019-09-17',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 33,
                    date: '2019-09-18',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-09-19',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 53,
                    date: '2019-09-20',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 4,
                    date: '2019-09-21',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-09-22',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-09-23',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2019-09-24',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 67,
                    date: '2019-09-25',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-09-26',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 13,
                    date: '2019-09-27',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-09-28',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 38,
                    date: '2019-09-29',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 10,
                    date: '2019-09-30',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 21,
                    date: '2019-10-01',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-10-02',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-10-03',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 30,
                    date: '2019-10-04',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2019-10-05',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-10-06',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 35,
                    date: '2019-10-07',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-10-08',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-10-09',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 33,
                    date: '2019-10-10',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-10-11',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 51,
                    date: '2019-10-12',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 38,
                    date: '2019-10-13',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 26,
                    date: '2019-10-14',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-10-15',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 62,
                    date: '2019-10-16',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-10-17',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 9,
                    date: '2019-10-18',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2019-10-19',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-10-20',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2019-10-21',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 31,
                    date: '2019-10-22',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 58,
                    date: '2019-10-23',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-10-24',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 5,
                    date: '2019-10-25',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 64,
                    date: '2019-10-26',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-10-27',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 46,
                    date: '2019-10-28',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 47,
                    date: '2019-10-29',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 17,
                    date: '2019-10-30',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 44,
                    date: '2019-10-31',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 8,
                    date: '2019-11-01',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 29,
                    date: '2019-11-02',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 41,
                    date: '2019-11-03',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 42,
                    date: '2019-11-04',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 15,
                    date: '2019-11-05',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 64,
                    date: '2019-11-06',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2019-11-07',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 3,
                    date: '2019-11-08',
                    weekday: 5,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-11-09',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 20,
                    date: '2019-11-10',
                    weekday: 0,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 34,
                    date: '2019-11-11',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 18,
                    date: '2019-11-12',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 27,
                    date: '2019-11-13',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 36,
                    date: '2019-11-14',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 49,
                    date: '2019-11-15',
                    weekday: 5,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 62,
                    date: '2019-11-16',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-11-17',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-11-18',
                    weekday: 1,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 54,
                    date: '2019-11-19',
                    weekday: 2,
                  },
                  {
                    color: '#239a3b',
                    contributionCount: 62,
                    date: '2019-11-20',
                    weekday: 3,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 31,
                    date: '2019-11-21',
                    weekday: 4,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 30,
                    date: '2019-11-22',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-11-23',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 22,
                    date: '2019-11-24',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 21,
                    date: '2019-11-25',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 40,
                    date: '2019-11-26',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 4,
                    date: '2019-11-27',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 25,
                    date: '2019-11-28',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 16,
                    date: '2019-11-29',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-11-30',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#7bc96f',
                    contributionCount: 43,
                    date: '2019-12-01',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 12,
                    date: '2019-12-02',
                    weekday: 1,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 37,
                    date: '2019-12-03',
                    weekday: 2,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 14,
                    date: '2019-12-04',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 19,
                    date: '2019-12-05',
                    weekday: 4,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 21,
                    date: '2019-12-06',
                    weekday: 5,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 21,
                    date: '2019-12-07',
                    weekday: 6,
                  },
                ],
              },
              {
                contributionDays: [
                  {
                    color: '#c6e48b',
                    contributionCount: 21,
                    date: '2019-12-08',
                    weekday: 0,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 24,
                    date: '2019-12-09',
                    weekday: 1,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 23,
                    date: '2019-12-10',
                    weekday: 2,
                  },
                  {
                    color: '#7bc96f',
                    contributionCount: 36,
                    date: '2019-12-11',
                    weekday: 3,
                  },
                  {
                    color: '#c6e48b',
                    contributionCount: 11,
                    date: '2019-12-12',
                    weekday: 4,
                  },
                ],
              },
            ],
          },
        },
      },
    },
  },
};
